import streamlit as st
from retriever import fetch_relevant_documents
from generator import generate_response

st.title("Legal Assistance Chatbot")
st.write("Ask questions about Indian law and get accurate, contextual answers.")

if "context" not in st.session_state:
    st.session_state["context"] = ""

query = st.text_input("Enter your legal question:")
if query:
    # Fetch relevant documents
    results = fetch_relevant_documents(query)
    context = "\n".join([doc['content'] for doc in results['documents']])
    st.session_state["context"] += context

    # Generate response
    response = generate_response(st.session_state["context"], query)
    st.write(response)

    # Add disclaimer
    st.write("**Disclaimer:** This response is generated by an AI system and may not be legally binding. Consult a qualified legal professional for advice.")
